### ISSUE TITLE
Add Moneropedia entries to Weblate

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#108]
https://github.com/monero-project/monero-site/issues/1780 is making Moneropedia entries translatable on Weblate. The PRs are slowly getting all merged. The .po and .pot files should be added on Weblate the same as it is now for user guides (https://translate.getmonero.org/projects/getmonero-user-guides/).

This is part of my CCS for working on getmonero.

**Comment by netrik182** [comment]
Hey @erciccione, may I close this issue? Moneropedia entries were added to Weblate: https://translate.getmonero.org/projects/getmonero-moneropedia/
