### ISSUE TITLE
Some words should be added into ENG-SimpCHN glossary

### ISSUE THREAD

**Issue by SorenEricMent** [monero-ecosystem/monero-translations#117]
The term stagenet is especially likely to be translated differently by different Chinese translators

Following are my suggestions
Mainnet 主网
Stagenet  预览网
Testnet 测试网

**Comment by netrik182** [comment]
Words added. Please let me know if you see something wrong. Thanks @SorenEricMent 

https://translate.getmonero.org/browse/monero/glossary/zh_Hans/?q=

**Comment by SorenEricMent** [comment]
Sorry but I, after carefully thought, want to change translation on Stagenet again...
镜像测试网 （"Mirror testnet" in Chinese）

Previous translators have already used the term "高仿测试网" in the translation of Monero GUI，but the term "高仿" sounds quite unnatural. Often related to things like Knockoffs or Copycats.

There aren't any single words in Chinese that could correspond "Stage" in this context, so I finally derived its meanings into two words.

Still, "高仿测试网" is acceptable to literally understand, so it's upon to you to choose. 预览 kinda deviated.
