### ISSUE TITLE
Spanish translation of "mining" is inconsistent across (and within) projects

### ISSUE THREAD

**Issue by ordtrogen** [monero-ecosystem/monero-translations#16]
In the GUI localization you'll find:
'minera' (probably spelling error)
'minado'
'minería'
Other projects use 'minado' (haven't checked closely)

Asking the Google:

"minería de criptomoneda" - 29 000 hits
"minado de criptomoneda" - 4 240 hits

Let's have @lh1008 , @BlackLotus64 and any other natives make a decision and then update all instances at the same time.

**Comment by lh1008** [comment]
Let's leave it as "minería", is a much common word. Agree with @ordtrogen .
