### ISSUE TITLE
[meta] Chinese translation needed to help an exchange list Monero

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#2]
@binaryFate wrote this on `#monero-translations` today:

*Hello Folks*
*I need somebody that speaks Chinese to translate ~1 page of text from English (today or tomorrow would be great). It is required to help a new exchange list Monero. Your contribution would be much appreciated :)*

You can contact him at binaryFate@getmonero.org so he can send you the document.

@Lafudoci @p1gd0g @bitOMG  Any of you guys can help with this?

I also [opened a task on Taiga](https://taiga.getmonero.org/project/erciccione-monero-localization/us/286?no-milestone=1)

**Comment by binaryFate** [comment]
Thanks @erciccione for posting. The text to translate is a broad description of Monero (that will be displayed on the exchange if they list Monero). It is not very long (~350 words my editor tells me).

I do not post details publicly by respect for the exchange.

Also helping them doing their job is not typically what we should do, but this time they asked nicely and I already provided the English version myself.

**Comment by Lafudoci** [comment]
@erciccione I'm happy to help with it. I'll contact @binaryFate by mail.

**Comment by erciccione** [comment]
Thanks @lafudoci :)

**Comment by erciccione** [comment]
If the work was done can i close this issue? @binaryFate

**Comment by binaryFate** [comment]
Yes, please close. Thanks again to @Lafudoci
