### ISSUE TITLE
Spanish translation of "Settings" discussion

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/monero-translations#22]
I would like to have an open discussion about this word.

I've seen several translations through the different texts already translated.

Settings

 - Configuraciones - Literal translation "configuration"
 - Ajustes - Literal translation "adjustments"
 - Opciones - Literal translation "option"

The `monero-wallet-gui` is using [opciones](https://www.youtube.com/watch?v=LbS2BJvPYfE&feature=youtu.be).

Found this sources with the translation for `Settings`:

Spanishdict uses [configuración](http://www.spanishdict.com/translate/settings) for computing but has more translations for the word.

Microsoft Terminology uses [configuración](https://www.microsoft.com/en-us/language/Search?&searchTerm=settings&langID=Spanish&Source=true&productid=All).

[Wordreference](http://www.wordreference.com/es/translation.asp?tranword=settings) gives several translations and definitions.

Google translator for the word "settings" by itself, gives the first translation for [ajustes](https://translate.google.com/?hl=es#en/es/settings). When adding a word, e.g. "command" or "open", with the word "settings", it gives the translation [configuración de comando](https://translate.google.com/?hl=es#en/es/command%20settings); [configuración abierta](https://translate.google.com/?hl=es#en/es/open%20settings). I know we "shouldn't" be using google but gives more references. 

What are your opinions?

**Comment by BlackLotus64** [comment]
I think it's just about to get to a shared opinion. I've been using "ajustes" since it was the first thing I thought, but all of the words are synonyms o anyone can be used.

I suggest we use either "configuración" or "opciones" since the last one is already being used in the GUI.

**Comment by erciccione** [comment]
Is this issue still relevant or can be closed?

**Comment by lh1008** [comment]
I would use "configuración" following a more computer tech terminology. What do you say @BlackLotus64, so we close this issue?

**Comment by lh1008** [comment]
This is open for a long time, will be closing it and adding "configuración" to the Spanish terminology and wait for more discussions if we have any.
