### ISSUE TITLE
Spanish translation for "View Only Wallet"

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/monero-translations#23]
Hi guys,

The `monero-wallet-gui` is using [Monedero de solo lectura](https://github.com/monero-project/monero-gui/blob/master/translations/monero-core_es.ts#L394).

Some of the translations are suggesting a different translation: 

[Monedero de visualización or/and Monedero de solo visualización](https://github.com/monero-project/monero-site/pull/799/files#diff-d5748730891e62e0001ed1254d4e1682R24)

What do you guys think?

**Comment by BlackLotus64** [comment]
I like more how "monedero de visualización" sounds, but as I said in other issue, it's about getting to a shared opinion, by voting or something like that.

Monedero de visualización would be "visualization wallet" literally.

**Comment by erciccione** [comment]
Is this issue still relevant or can be closed?

**Comment by BlackLotus64** [comment]
It can be closed in my opinion :)

**Comment by erciccione** [comment]
Closing, In case it can be rediscussed on #9 . So to have only one issue open for discussions about the same language.
