### ISSUE TITLE
Provide a way to use localized versions of the videos in getmonero.org

### ISSUE THREAD

**Issue by vp1111** [monero-ecosystem/monero-translations#40]
Monero's website (https://getmonero.org/) has some videos that are kept in English even when visiting the localized version of a page (e.g. the homepage). Actually there's no way for translators and other contributors to propose a localized version of the video. A member of the Brazilian Community did a voice-over and post-edit on the video translating it completely to Portuguese. We would like to use that video for the localized version of the homepage.

**Comment by erciccione** [comment]
Suggested a solution on the getmonero repo: https://repo.getmonero.org/monero-project/monero-site/issues/952

**Comment by erciccione** [comment]
Closing this, we can keep only the issue on gitlab for tracking.

**Comment by erciccione** [comment]
@vp1111 could you send me the pt-br video again? I can't remember where i uploaded it.
