### ISSUE TITLE
Migrate all terminology guides from Taiga to this repo

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#5]
Migrating all terminology guides from Taiga to `monero-translations` this will give us a better manageable commit history and will avoid the guide to be borked by contributors who mess up with markdown

- [x] **Swedish** - Should be Borked IIRC, @ordtrogen can you confirm? would you submit a new one in this repository?
- [x] **Italian**
- [x] **German**
- [x] **French**
- [x] **Spanish** - Borked, need to be submitted. Pinging @lh1008 (i already spoke with Diffusive on IRC about this)

**Comment by ordtrogen** [comment]
Sounds good

**Comment by lh1008** [comment]
The bork thing usually happens when you are updating it through markdown or when you "add" more cells. When I first did the instance for the User Story I had several issues with the same thing. :)

**Comment by erciccione** [comment]
@ordtrogen what do you think about moving the guide as it is on Monero Taiga and then edit it in a later moment if it needs so? so i can just remove the guides from taiga and just point to here from there

**Comment by ordtrogen** [comment]
The last couple days have been very hectic but I can do it right away. 
Will post a PR in a moment

**Comment by erciccione** [comment]
This is done! Thanks! :)
