### ISSUE TITLE
Localization Workgroup meeting: 3 May @ 16:00 UTC

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#51]
As anticipated during last Monero Community Meeting, i would like to organize a meeting of the Localization Workgroup.

The two main points will be:

- Pootle: Should we keep using it even if the projects itself it's almost dead (since the functionalities we need seems to work fine at the moment)? If not, what other platform should we use? How much effort should i (we) put into this migration if deemed necessary?
- GUI workflow: Some GUI devs think we can organize a better and more efficient workflow to handle translations, for the GUI. I'm open to every improvement, so i think it's necessary to make a clear overview on how translations are handled at the moment on both sides, so that we can improve our system if necessary.

If somebody wants to add other points or have comments, go ahead!

**Comment by selsta** [comment]
Regarding GUI, looks like it’s possible to turn of the line numbers: https://stackoverflow.com/a/29964486

This would solve the issue with translations getting out of sync.

**Comment by erciccione** [comment]
@selsta That would actually solve a lot of time, since at the moment I have to refresh the language files even if the actual strings don't change, for that very reason. Great to know!

**Comment by el00ruobuob** [comment]
But wouldn't it need the strings to be unique?

**Comment by erciccione** [comment]
Opened issue in monero-project/meta: monero-project/meta#339

**Comment by erciccione** [comment]
Logs of the meeting:https://repo.getmonero.org/monero-project/monero-site/merge_requests/1067
