### ISSUE TITLE
Comments on French terminology

### ISSUE THREAD

**Issue by ghost** [monero-ecosystem/monero-translations#61]
Hello,
Is there already a rule for the plural of monero ?
In french, we write "les euros, les dollars", etc.
So I would use "les moneros".
Do you consider that ok ?

**Comment by el00ruobuob** [comment]
The proper plural would be "moneroj" as monero is an esperanto word. That's valid for every language.

**Comment by el00ruobuob** [comment]
However, monero could be used intact for plural, and I don't like the "moneros" variant.

**Comment by erciccione** [comment]
Closing.
