### ISSUE TITLE
Collaboration with bisq project (2 short translations needed)

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#62]
I recently made [a PR for the bisq website](https://github.com/bisq-network/bisq-website/pull/221), i think would be cool to see some collaboration between Monero and Bisq, since, in my opinion, the 2 are complementary to each other.

We need a couple of strings to be translated:

`Through last month` - context: *We had 1000 visitors through last month*
`As of last month` - context: *twitter users: 500. as of last month*

The translation is needed in **Spanish (@lh1008 @BlackLotus64 ), German (@rodolfo912 @wobole), Portuguese (pt-pt) (@rmbb @vp11 @malmen) and Chinese simplified (@equim-chan @4broaf @hqwrong)**. Please provide the translation down here and i will add it to my PR, adding credits to the translators and the Monero community.

**Comment by BlackLotus64** [comment]
Sure, I'll take a look at it today, thanks for the ping @erciccione.

**Comment by lh1008** [comment]
Hey @erciccione,

Here are my options:
 
`Through las month` - "Durante el mes pasado.
`As of last month` - "Desde el mes pasado" - "A partir del mes pasado"

@BlackLotus64 what do you think?

**Comment by BlackLotus64** [comment]
> 
> 
> Hey @erciccione,
> 
> Here are my options:
> 
> `Through las month` - "Durante el mes pasado.
> `As of last month` - "Desde el mes pasado" - "A partir del mes pasado"
> 
> @BlackLotus64 what do you think?

Sounds good, something I would have come with.

Jeez, I was looking at the PR in Bisq thinking some more strings needed translation.

**Comment by Wobole** [comment]
I would suggest...

``Through last month`` - "Während des letzten Monats"
``As of last month`` - "Bis Ende [des] letzten Monats"

... although it may sound a bit too stilted, so: improvement suggestions are welcome.

**Comment by erciccione** [comment]
Thanks everybody for the help. Now we only need **PT-pt** and **ZH-cn**. I'm gonna leave here a screenshot of how the page will show up, so that the contest is clear without the need to go through the PR on bisq:

![Screenshot from 2019-09-02 10-54-26](https://user-images.githubusercontent.com/28106476/64102440-85176180-cd5f-11e9-9f9d-71f0817ea5dd.png)

**Comment by huey735** [comment]
@lh1008 I think
"Hasta el mes pasado" for "As of last month" may be a better translation. As the sentence is supposed to represent the number up until that moment.

@erciccione here's for Portuguese (PT)

pTotalDate: Durante o mês passado
pToDate: Até o mês passado

**Comment by ArnaudFR86** [comment]
pTotalDate: Au cours du mois dernier
pToDate: Depuis le mois dernier

**Comment by erciccione** [comment]
bisq-network/bisq-website#221 has been merged. Thanks everybody for the help :)
