### ISSUE TITLE
Vi_vn for GUI wallet

### ISSUE THREAD

**Issue by klpohuy1998** [monero-ecosystem/monero-translations#66]
I want to contribute Vietnamese translation for GUI wallet, how can I do it?

**Comment by erciccione** [comment]
Hi @klpohuy1998. I don't know if you already found the solution, but the GUI wallet is translatable here: https://translate.getmonero.org/projects/monero/gui-wallet/

We don't have any translation in Vietnamese yet, but would be cool to have it! Let me know if you are still interested.

**Comment by erciccione** [comment]
Nevermind, i just ansered to your email

(It's now possible to translate the GUI into vietnamese: https://translate.getmonero.org/projects/monero/gui-wallet/vi/)
