### ISSUE TITLE
Terminology Guide: pt-BR updates

### ISSUE THREAD

**Issue by netrik182** [monero-ecosystem/monero-translations#68]
Based on a recent talk I had with @erciccione on `#monero-translations`, I'm opening this issue to foster the discussion about updating and adding some new terms into the [Brazilian Portuguese Terminology Guide.](https://github.com/monero-ecosystem/monero-translations/blob/master/terminology-guides/portuguese-br-terminology.md)

Below you can find the current version of this repo and the **bolted** entries are the terms suggested to be added/changed:

## Glossary For Brazilian Portuguese Translations

| **Original** | **Tradução** | **Comentários** |
| --- | --- | --- |
| Account | Conta | |
| Anonimity set | Conjunto de anonimato |  |
| Blackball | Blackball (substantivo), Banir (quando verbo) | |
| Blockchain | Blockchain | Mantém a palavra em inglês, gênero feminino (a blockchain) |
| **Blockchain pruning** | ~~Poda de blockchain~~ Compactação de blockchain |  |
| Block height | Altura do bloco |  |
| Block reward | Recompensa do bloco |  |
| Block time | Tempo do bloco |  |
| **CLI Wallet** | Carteira CLI | Termo já usando em outros materiais |
| Commit | Confirmação (substantivo), Confirmar (quando verbo) | |
| Commitment | Comprometimento | |
| Daemon | Daemon | Mantém a palavra em inglês |
| Decoy | Chamariz | Termo já usando em outros materiais |
| Dust | Ínfimo | No sentido de quantidade/valor. Valores pequenos que normalmente são menores do que a taxa para movê-los. |
| Fork | Fork | Mantém a palavra em inglês |
| Full node | Nó completo | |
| Fungible | Fungível | |
| Grassroots Community | ~~Comunidade de base~~ **Comunidade Raiz** |  | 
| GUI Wallet | Carteira GUI | Termo já usando em outros materiais |
| Hard fork | Hard fork | Mantém a palavra em inglês |
| **Hardware Wallet** | Carteira de Hardware | Dependendo do contexto pode ser usado "Dispositivo físico" |
| Input | Entrada | Quando o termo se refere a uma transação |
| Integrated address | Endereço integrado | |
| Issuer | Emissor |  |
| Key Image | Imagem-chave | |
| Ledger | Livro razão |  |
| Ledger Wallet | Carteira Ledger |  |
| **Long payment ID** | ID do pagamento longo | |
| Mine (To) | Minerar | |
| Miner | Minerador | |
| **Mixing** | Mixing ou mistura |
| Mnemonic seed | Semente mnemônica | |
| Monero Research Lab | Laboratório de Pesquisa Monero |  |
| Multisig | Multisig | Utilizar em forma de "sigla" ou a tradução abaixo |
| Multisignature | Assinatura múltipla | |
| Node | Nó | |
| One-time Address | Endereço de uso único | |
| Output | Saída | Quando o termo se refere a uma transação |
| Paper wallet | Carteira em papel | |
| **Payment ID** | ID do pagamento | |
| Pedersen('s) Commitment | Comprometimento de Pedersen | |
| Pool | Pool | Mantém a palavra em inglês, gênero feminino (a pool) |
| **Primary address** | Endereço primário | |
| Proof-of-work | Prova de trabalho |  |
| Range Proof(s) | Prova de intervalo | |
| **Pruned node** | Nó compactado |  |
| **Pruning** | Compactação |  |
| **Range Proof(s)** | Prova(s) de intervalo | |
| Restore height | Altura de restauração | |
| RingCT | RingCT | Utilizar em forma de "sigla" ou a tradução abaixo |
| Ring confidential transaction | Transações confidenciais em anel |  |
| Ring Member | Membro do anel |  |
| Ring signatures | Assinaturas em anel | |
| Ringsize | Tamanho do anel |  |
| Recipient | Destinatário | |
| Seed | Semente |  |
| Sender | Remetente | |
| Signer | Signatário | |
| Spend Key | Chave de gasto | |
| Stealth address | Endereços sigilosos | Terminologia antiga: Endereços _stealth_ |
| Subaddress | Subendereço | |
| Sweep | Limpeza (substantivo), Limpar (quando verbo) | |
| Tail emission | Emissão em cauda | |
| Transaction unlock time | Tempo de desbloqueio da transação | |
| Unblackball | Desbanir | |
| Unmixable | Não-misturável |  |
| Untraceable | Não-rastreável | |
| View-Only | Somente leitura | |
| View Key | Chave de visualização | |
| Wallet | Carteira | |
| **Whitepaper** | White paper |  |

**Comment by erciccione** [comment]
@netrik182 I think enough time has passed. Feel free to PR the new terms to `portuguese-br-terminology.md`
