### ISSUE TITLE
Translation platform down

### ISSUE THREAD

**Issue by comradekingu** [monero-ecosystem/monero-translations#72]
https://translate.getmonero.org/projects/monero/

![bilde](https://user-images.githubusercontent.com/13802408/82890043-1b696400-9f3b-11ea-8e2c-714fc4ed2741.png)

**Comment by erciccione** [comment]
Thank you for the report @comradekingu. I was upgrading Weblate to the latest version. This was a major upgrade so it took slightly longer than usual (about 15 minutes). Now everything should be working as normal, please let me know if that's not the case please :)
