### ISSUE TITLE
Add kingu as reviewer

### ISSUE THREAD

**Issue by comradekingu** [monero-ecosystem/monero-translations#75]
https://translate.getmonero.org/user/kingu/

**Comment by erciccione** [comment]
Hi @comradekingu. As i explained on IRC. The "Reviewer" status on Weblate is only given to trusted members of the Monero Localization workgroup who volunteer for the role. These volunteer have a lot of experience with Monero translations and have been around enough to be trusted for the role.

Sorry but i don't know you and i hav to reject your proposal, but you are welcome to participate to the wrkgroup :)

**Comment by comradekingu** [comment]
How does one participate in the workgroup?
