### ISSUE TITLE
Add subtitles for Monero Means Money on Weblate

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/monero-translations#77]
Now that we have the final structure (#69 and #70) and some translations, we can add the subtitles on Weblate.

I will create a new component called "Community", that will be used for selected translatable content made by the community.

@intj440 and @netrik182 if you are interested i could give you reviewer powers for the subtitles on Weblate. It would give you direct control over the work of translators.

**Comment by erciccione** [comment]
I opened this issue as a personal reminder and to discuss the best way to manage the project (in weblate terminology).

**Comment by netrik182** [comment]
Yes, please. I'll be glad to help as reviewer.

**Comment by erciccione** [comment]
https://translate.getmonero.org/projects/community/monero-means-money/

@netrik182 I added you as reviewer for all languages. Please let me know if everything is ok.

Leaving this open, because we should say that the subtitles should now be translated on Weblate

**Comment by erciccione** [comment]
We should also announce this on reddit and twitter 

ping @samsunggalaxyplayer FYI

**Comment by erciccione** [comment]
This is resolved.
